name: immich-wather

services:
  server:
    image: ghcr.io/siganberg/immich-watcher:1.0.16
    container_name: immich_wather
    environment:
      - IMMICH_INSTANCE_URL=${IMMICH_INSTANCE_URL}
      - IMMICH_API_KEY=${IMMICH_API_KEY}
    restart: always
    volumes:
      - /Users/francis.marasigan/immich-watcher:/var/lib/data
