name: immich-watcher

services:
  server:
    image: immich-watcher:1.0
    container_name: immich_wather
    environment:
      - IMMICH_INSTANCE_URL=${IMMICH_INSTANCE_URL}
      - IMMICH_API_KEY=${IMMICH_API_KEY}
    restart: always
    volumes:
      - /Users/francis.marasigan/immich-watcher:/var/lib/data
