name: Build and Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build 
    permissions:
      id-token: write
      contents: write
      checks: write
      issues: write
      pull-requests: write
    
    runs-on: ubuntu-latest

    env:
      DOTNET_INSTALL_DIR: "path/to/directory"
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Build and Test
      run:  dotnet build src/  -c Release
      
    #- name: Test Report
    #  uses: dorny/test-reporter@v1
    #  if: success() || failure()   
    #  with:
    #    name: Test Report     
    #    path: "**/test-results.trx"   
    #    reporter: dotnet-trx

    #- name: Code Coverage Report
    #  uses: irongut/CodeCoverageSummary@v1.3.0
    #  with:
    #    filename: test_results/**/coverage.cobertura.xml
    #    badge: true
    #    fail_below_min: true
    #    format: markdown
    #    hide_branch_rate: false
    #    hide_complexity: true
    #    indicators: true
    #    output: both
    #    thresholds: '60 80'

    #- name: Add Coverage PR Comment
    #  uses: marocchino/sticky-pull-request-comment@v2
    #  if: github.event_name == 'pull_request'
    #  with:
    #    recreate: true
    #    path: code-coverage-results.md

    #- name: Write to Job Summary
    #  run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY